import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source = fs.readFileSync('js/core/94-cakisma.js', 'utf8');
const window = {};
vm.runInNewContext(source, { window, JSON, Set, Array, Object });
const api = window.tf4Cakisma;
const temel = { baslik: 'Eski', etiket: ['a'], ortak: 'aynı' };
const yerel = { baslik: 'Benim', etiket: ['a', 'b'], ortak: 'aynı' };
const uzak = { baslik: 'Uzak', etiket: ['a'], ortak: 'aynı', yeni: true };
const fark = api.fark(yerel, uzak, temel);
assert.equal(fark.find((x) => x.alan === 'baslik').cakisma, true);
assert.equal(fark.find((x) => x.alan === 'etiket').cakisma, false);
assert.equal(fark.find((x) => x.alan === 'yeni').uzakDegisti, true);
const sonuc = api.birlestir(yerel, uzak, { baslik: 'yerel', etiket: 'uzak' });
assert.equal(sonuc.baslik, 'Benim');
assert.deepEqual(sonuc.etiket, ['a']);
assert.equal(sonuc.yeni, true);
console.log('Shared-universe field diff and explicit local/remote merge: PASS');
